name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: Syncing OAS
        uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi ./swagger.json --key=${{ secrets.README_OAS_TEST }} --id=6636eacf7f8986900170bb1f3
      
      - name: Syncing Docs
        uses: readmeio/rdme@7.2.0
        with:
          rdme: docs ./singledoc --key=${{ secrets.README_OAS_TEST }} --version=1.0