name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main
      #adding branch back
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # - name: Creating Version
      #   uses: readmeio/rdme@8.6.6
      # with:
      #   rdme: versions:create v14.0 --key=${{secrets.README_OAS_TEST}} --fork=v3.0 --main=false --beta=false --isPublic=true --deprecated=false

      # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      # - name: Checking OAS
      #    uses: readmeio/rdme@v8
      #    with:
      #    rdme: openapi:inspect ./swagger.json

      # - name: Syncing Docs
      #   uses: readmeio/rdme@v8
      #   with:
      #     rdme: docs documents --key=${{ secrets.README_OAS_TEST }} --version=1.0

      - name: Sync to trainingproj2024
        uses: readmeio/rdme@v9
        with:
          rdme: openapi ./my-test.json --key=${{ secrets.LEGACY_OAS_KEY }} --version=5.0 --create

      # - name: Sync to myproducttest
      #   uses: readmeio/rdme@v10
      #   with:
      #     rdme: openapi upload ./my-test.json  --key=${{ secrets.README_OAS_TEST2 }}
